server {
    listen 5174;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /monitor/ {
        try_files $uri $uri/ /monitor/index.html;
    }

    location /api/log/ {
        proxy_pass http://log-monitor-service:8200/api/log/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
